In [1]:
# Check with people which is the correct pedestal file to use
# make sure that the unique id -> pixel id is taking into account the tile swaps
# why does the pedestal file have channels that are supposed to be nonrouted?
# it looks like the pedestal file I'm using is using tile number instead of io_channel

In [2]:
import json
import numpy as np
import tqdm
import matplotlib.pyplot as plt

In [3]:
with open('/global/common/software/dune/mkramer/devel/flow4pedestal/reference-cold-pedestal-2024_06_05_08_28_19_CDTevd_ped.tile_id.decimal.json', 'r') as f:
    data = json.load(f)
    

In [4]:
def unique_channel_id(d):
    return ((d['io_group'].astype(int)*10000+((d['io_channel'].astype(int)-1)//4)+1)*1000 \
            + d['chip_id'].astype(int))*100 + d['channel_id'].astype(int)

def unique_to_channel_id(unique):
    return unique % 100

def unique_to_chip_id(unique):
    return (unique// 100) % 1000

def unique_to_io_channel(unique):
    return(unique//(100*1000)) % 1000

def unique_to_tiles(unique):
    return ( (unique_to_io_channel(unique)-1) // 4) + 1

def unique_to_io_group(unique):
    return(unique // (100*1000*10000)) % 10000

In [12]:
def convert_unique_id(unique_id):
    io_group = (unique_to_io_group(unique_id) - 1) % 2 + 1
    tile_id = (unique_to_io_channel(unique_id) - 1) % 8 + 1
    chip_id = unique_to_chip_id(unique_id)
    channel_id = unique_to_channel_id(unique_id)

    convert = (
        (io_group*10000+tile_id)*1000 \
            + chip_id)*100 + channel_id

    return convert

In [6]:
with open('uniqueid_to_pixelid_v2a.json', 'r') as file:
    unique_id_to_pixel_id_v2a = json.load(file)
with open('uniqueid_to_pixelid_v2b.json', 'r') as file:
    unique_id_to_pixel_id_v2b = json.load(file)

In [7]:
np.unique(unique_to_channel_id(np.array(list(data.keys()), dtype=int)), return_counts=True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]),
 array([6360, 6360, 6360, 6357, 6354, 6354, 1604, 1596, 1613, 1607, 6362,
        6361, 6359, 6359, 6360, 6359, 6364, 6363, 6358, 6360, 6360, 6358,
        1604, 1602, 1623, 1603, 6359, 6361, 6360, 6355, 6361, 6358, 6364,
        6360, 6363, 6358, 6357, 6361, 1604, 1601, 1627, 6360, 6359, 6356,
        6360, 6355, 6360, 6358, 6362, 6358, 6362, 6357, 6357, 6358, 1605,
        1601, 1613, 1605, 6361, 6356, 6359, 6358, 6361, 6362]))

In [8]:
np.unique(unique_to_chip_id(np.array(list(data.keys()), dtype=int)), return_counts=True)

(array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
        105, 106, 107, 108, 109, 110, 111, 112, 113, 115, 116, 120, 121,
        122, 123, 124, 125, 126, 134, 138, 141, 147, 149, 161, 177, 178,
        192, 203, 207, 248]),
 array([  28,    3,    5,    2,    3,   25,   16,   13,   16,    1, 3327,
        3334, 3328, 3326, 3374, 3375, 3376, 3376, 3304, 3327, 3378, 3333,
        3378, 3376, 3376, 3377, 3381, 3376, 3345, 3386, 3380, 3376, 3390,
        3313, 3376

In [9]:
np.unique(unique_to_io_channel(np.array(list(data.keys()), dtype=int)))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [10]:
np.unique(unique_to_io_channel(np.array(list(unique_id_to_pixel_id_v2a.keys()), dtype=int)))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
i = 0
pixel_ids = [[],[],[],[]] 
pedestals = [[],[],[],[]]
nonrouted_v2a_channels = [6, 7, 8, 9, 22, 23, 24, 25, 38, 39, 40, 54, 55, 56, 57]


for k, v in data.items():
    
    
    # unique_id = int(k)
    pedestal = v['pedestal_mv']

    unique_id = int(k)

    unique_iog = unique_to_io_group(unique_id)
    chip_id = unique_to_chip_id(unique_id)
    converted_unique_id = convert_unique_id(unique_id)
    channel_id = unique_to_channel_id(unique_id)
    # tile_id = unique_to_io_channel(unique_id)
    

    if chip_id not in range(11,111):
        continue
        
    if (unique_iog in [1,2]) and (channel_id not in nonrouted_v2a_channels):
        mod = 0
        buff = 0
        pixel_id = buff + unique_id_to_pixel_id_v2a[str(converted_unique_id)]
        
    elif (unique_iog in [3,4]) and (channel_id not in nonrouted_v2a_channels) :
        mod = 1
        buff = 7*10*2 * 7*10*4 * 2
        pixel_id = buff + unique_id_to_pixel_id_v2a[str(converted_unique_id)]
        
    elif (unique_iog in [5,6]) :
        mod = 2
        buff = 8*10*2 * 8*10*4 * 2 * 2
        pixel_id = buff + unique_id_to_pixel_id_v2b[str(converted_unique_id)]
        
    elif (unique_iog in [7,8]) and (channel_id not in nonrouted_v2a_channels):
        mod = 3
        buff = 7*10*2 * 7*10*4 * 2 * 3
        pixel_id = buff + unique_id_to_pixel_id_v2a[str(converted_unique_id)]
        
    else:
        continue
    try:
        pixel_ids[mod].append(pixel_id)
        pedestals[mod].append(pedestal)
    except:
        break
        
    i+=1

for i in range(4):
    print(i)
    out_file = 'pedestals_module{i}.npz'.format(i=i)
    keys = np.array(pixel_ids[i], dtype='int64')
    values = np.array(pedestals[i], dtype='float64')
    default = np.array([580.])
    np.savez(out_file, keys=keys, values=values, default=default)
# print(pixel_ids)

0
1
2
3


In [7]:
print( np.array(pixel_ids[0]).min(), np.array(pixel_ids[0]).max())
print( np.array(pixel_ids[1]).min(), np.array(pixel_ids[1]).max())
print( np.array(pixel_ids[2]).min(), np.array(pixel_ids[2]).max())
print( np.array(pixel_ids[3]).min(), np.array(pixel_ids[3]).max())

0 78399
78400 156799
204800 307199
235200 313599


In [15]:
#The below is using the json files Jaafar made me. The above uses files I generated through MapPixelIDToUniqueID_2x2.ipynb

(77990,)

In [6]:
with open('uniqueid_to_pixelid_mod0.json', 'r') as file:
    unique_id_to_pixel_id_mod0 = json.load(file)
with open('uniqueid_to_pixelid_mod1.json', 'r') as file:
    unique_id_to_pixel_id_mod1 = json.load(file)
with open('uniqueid_to_pixelid_mod2.json', 'r') as file:
    unique_id_to_pixel_id_mod2 = json.load(file)
with open('uniqueid_to_pixelid_mod3.json', 'r') as file:
    unique_id_to_pixel_id_mod3 = json.load(file)

In [7]:
i = 0
pixel_ids = [[],[],[],[]] 
pedestals = [[],[],[],[]]
nonrouted_v2a_channels = [6, 7, 8, 9, 22, 23, 24, 25, 38, 39, 40, 54, 55, 56, 57]


for k, v in data.items():
    
    
    # unique_id = int(k)
    pedestal = v['pedestal_mv']

    unique_id = int(k)

    unique_iog = unique_to_io_group(unique_id)
    chip_id = unique_to_chip_id(unique_id)
    converted_unique_id = convert_unique_id(unique_id)
    channel_id = unique_to_channel_id(unique_id)
    # tile_id = unique_to_io_channel(unique_id)
    

    if chip_id not in range(11,111):
        continue

        
    if (unique_iog in [1,2]) and (channel_id not in nonrouted_v2a_channels):
        mod = 0
        buff = 0
        pixel_id = buff + unique_id_to_pixel_id_mod0[str(converted_unique_id)]
        
    elif (unique_iog in [3,4]) and (channel_id not in nonrouted_v2a_channels) :
        mod = 1
        buff = 7*10*2 * 7*10*4 * 2
        pixel_id = buff + unique_id_to_pixel_id_mod1[str(converted_unique_id)]
        
    elif (unique_iog in [5,6]) :
        mod = 2
        buff = 8*10*2 * 8*10*4 * 2 * 2
        pixel_id = buff + unique_id_to_pixel_id_mod2[str(converted_unique_id)]
        
    elif (unique_iog in [7,8]) and (channel_id not in nonrouted_v2a_channels):
        mod = 3
        buff = 7*10*2 * 7*10*4 * 2 * 3
        pixel_id = buff + unique_id_to_pixel_id_mod3[str(converted_unique_id)]
        
    else:
        continue
    # print(k, unique_id)
    try:
        pixel_ids[mod].append(pixel_id)
        pedestals[mod].append(pedestal)
    except:
        print(unique_id, converted_unique_id)
        print(unique_iog, tile_id, chip_id, channel_id)
        break
        
    # print(unique_id, pedestal, unique_iog)
    # print(unique_id_to_pixel_id_v2a[k])
    i+=1


for i in range(4):
    print(i)
    out_file = 'pedestals_module{i}.npz'.format(i=i)
    keys = np.array(pixel_ids[i], dtype='int64')
    values = np.array(pedestals[i], dtype='float64')
    default = np.array([580.])
    np.savez(out_file, keys=keys, values=values, default=default)
# print(pixel_ids)

0
1
2
3


In [12]:
print( np.array(pixel_ids[0]).min(), np.array(pixel_ids[0]).max())
print( np.array(pixel_ids[1]).min(), np.array(pixel_ids[1]).max())
print( np.array(pixel_ids[2]).min(), np.array(pixel_ids[2]).max())
print( np.array(pixel_ids[3]).min(), np.array(pixel_ids[3]).max())

0 78399
78400 156799
204800 307199
235200 313599
